Seth's Income:
  - 
  - New Entry
  - Main Income
  - Side Income
Alexa's Income:
  - 
  - New Entry
  - Main Income
  - Side Income
Housing:
  - 
  - New Entry
  - Rent
  - Mortgage
  - HOA
Utilities:
  - 
  - New Entry
  - Electric
  - Gas
  - Water
  - Internet
  - Trash and Recycling
Savings:
  - 
  - New Entry
  - Vacation
  - Retirement
  - House
  - Car
  - Wedding
  - Emergency
Debt:
  - 
  - New Entry
  - Student Loan
  - Credit Card
Automotive:
  - 
  - New Entry
  - Car Payment
  - Fuel
  - Car Wash
Groceries:
  - 
  - New Entry
  - Walmart
  - Aldi
  - Target
  - Publix
Insurance:
  - 
  - New Entry
  - Car Insurance
  - Health Insurance
  - Home Insurance
Restaurants:
  - 
  - New Entry
  - McDonald's
  - Taco Bell
Pet Supplies:
  - 
  - New Entry
  - Pet Food
  - Treats
  - Toys
Personal:
  - 
  - New Entry
  - Electronics
  - Tools
  - Games
Dates:
  - 
  - New Entry
  - Dinner
  - Activity
Entertainment:
  - 
  - New Entry
  - Movies
  - Zoo
  - Theme Park
Misc Necessities:
  - 
  - New Entry
  - Clothes
  - Cleaning Supplies
  - School Supplies
Gifts:
  - 
  - New Entry
  - Birthday
  - Christmas
  - Random