? ''
: - null
Alexa's Income:
- null
- New Entry
- Main Income
- Side Income
Automotive:
- null
- New Entry
- Car Payment
- Fuel
- Car Wash
- Maintenance
Dates:
- null
- New Entry
- Dinner
- Activity
- Movies
Debt:
- null
- New Entry
- Student Loan
- Credit Card
- Water Filter
Entertainment:
- null
- New Entry
- Movies
- Zoo
- Theme Park
- Board Games
Gifts:
- null
- New Entry
- Birthday
- Christmas
- Random
- Wedding
Groceries:
- null
- New Entry
- Walmart
- Aldi
- Target
- Publix
- 7/11
- "BJ\u2019s"
- Other
- Dollar General
Housing:
- null
- New Entry
- Rent
- Mortgage
- HOA
Insurance:
- null
- New Entry
- Car Insurance
- Health Insurance
- Home Insurance
Medical:
- null
- New Entry
- Pregnancy
- Checkup
- Medication
- Psychological
- Small Visit
- Medium Visit
- Large Visit
Misc Necessities:
- null
- New Entry
- Clothes
- Cleaning Supplies
- School Supplies
- Other
Personal:
- null
- New Entry
- Electronics
- Tools
- Games
Pet Supplies:
- null
- New Entry
- Pet Food
- Treats
- Toys
Restaurants:
- null
- New Entry
- McDonald's
- Taco Bell
- KFC
- Chick-Fil-A
- Lockheed Martin Cafeteria
- Chipotle
- Whole Foods
- Burger King
- Other
- "Mama Romano\u2019s"
- "Dunkin\u2019 Donuts"
- Perkins
- "Wendy\u2019s"
- Baskin Robbins
- Twistee Treat
- Papa Johns
- Star Bucks
- On the Border
- Airport Food
- Panera Bread
Savings:
- null
- Retirement
- Other
Seth's Income:
- null
- New Entry
- Main Income
- Side Income
Utilities:
- null
- New Entry
- Electric
- Gas
- Water
- Internet
- Trash and Recycling
Vacation:
- null
- New Entry
- Food
- Transportation
- Lodging
- Entertainment
